export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const POSTS_ROUTE = '/post'
export const POST_ROUTE = '/post/:id'
export const CREATE_POST_ROUTE = '/create_post'
export const LOGOUT_ROUTE = '/logout'
