export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const POSTS_ROUTE = '/posts'
export const POST_ROUTE = '/post'
export const CREATE_POST_ROUTE = '/create_post'
